name: Build and Push

on:
  push:
    branches:
      - main
      - release
    tags:
      - 'v*'

env:
  IMAGE: ${{ secrets.DOCKER_USERNAME }}/md-docs

jobs:
  check:
    name: Build front-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - id: bun
        name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run typecheck and tests
        run: |
          cp .env.example .env
          bun --bun run check
      - name: Build Bundle
        run: bunx --bun vite build
      - id: meta
        name: Extract metadata (tags, labels)
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,value=edge,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=next,enable=${{ github.ref == 'refs/heads/release' }}
            type=semver,pattern=v{{major}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{version}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        id: build-x64
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUN_VERSION=${{ steps.bun.outputs.bun-version }}
          cache-from: type=registry,ref=${{ env.IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}:buildcache,mode=max
